
package at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SyblAPIService", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SyblAPIService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "scalein", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.Scalein")
    @ResponseWrapper(localName = "scaleinResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.ScaleinResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/scaleinRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/scaleinResponse")
    public void scalein(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Test")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Test", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.Test")
    @ResponseWrapper(localName = "TestResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.TestResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/TestRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/TestResponse")
    public String test();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "scaleout", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.Scaleout")
    @ResponseWrapper(localName = "scaleoutResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.ScaleoutResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/scaleoutRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/scaleoutResponse")
    public void scaleout(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setControlledService", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.SetControlledService")
    @ResponseWrapper(localName = "setControlledServiceResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.SetControlledServiceResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/setControlledServiceRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/setControlledServiceResponse")
    public void setControlledService(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentCPUSize", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentCPUSize")
    @ResponseWrapper(localName = "getCurrentCPUSizeResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentCPUSizeResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentCPUSizeRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentCPUSizeResponse")
    public Float getCurrentCPUSize(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCostPerHour", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCostPerHour")
    @ResponseWrapper(localName = "getCostPerHourResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCostPerHourResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCostPerHourRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCostPerHourResponse")
    public Float getCostPerHour(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentRAMSize", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentRAMSize")
    @ResponseWrapper(localName = "getCurrentRAMSizeResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentRAMSizeResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentRAMSizeRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentRAMSizeResponse")
    public Float getCurrentRAMSize(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentMemUsage", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentMemUsage")
    @ResponseWrapper(localName = "getCurrentMemUsageResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentMemUsageResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentMemUsageRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentMemUsageResponse")
    public Float getCurrentMemUsage(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTotalCostSoFar", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetTotalCostSoFar")
    @ResponseWrapper(localName = "getTotalCostSoFarResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetTotalCostSoFarResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getTotalCostSoFarRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getTotalCostSoFarResponse")
    public Float getTotalCostSoFar(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @return
     *     returns at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.Node
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getControlledService", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetControlledService")
    @ResponseWrapper(localName = "getControlledServiceResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetControlledServiceResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getControlledServiceRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getControlledServiceResponse")
    public Node getControlledService();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentReadLatency", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentReadLatency")
    @ResponseWrapper(localName = "getCurrentReadLatencyResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentReadLatencyResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentReadLatencyRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentReadLatencyResponse")
    public Float getCurrentReadLatency(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentReadCount", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentReadCount")
    @ResponseWrapper(localName = "getCurrentReadCountResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentReadCountResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentReadCountRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentReadCountResponse")
    public Float getCurrentReadCount(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentWriteLatency", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentWriteLatency")
    @ResponseWrapper(localName = "getCurrentWriteLatencyResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentWriteLatencyResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentWriteLatencyRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentWriteLatencyResponse")
    public Float getCurrentWriteLatency(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentWriteCount", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentWriteCount")
    @ResponseWrapper(localName = "getCurrentWriteCountResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentWriteCountResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentWriteCountRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentWriteCountResponse")
    public Float getCurrentWriteCount(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentCPUUsage", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentCPUUsage")
    @ResponseWrapper(localName = "getCurrentCPUUsageResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentCPUUsageResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentCPUUsageRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentCPUUsageResponse")
    public Float getCurrentCPUUsage(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentHDDSize", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentHDDSize")
    @ResponseWrapper(localName = "getCurrentHDDSizeResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentHDDSizeResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentHDDSizeRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentHDDSizeResponse")
    public Float getCurrentHDDSize(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentLatency", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentLatency")
    @ResponseWrapper(localName = "getCurrentLatencyResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentLatencyResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentLatencyRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentLatencyResponse")
    public Float getCurrentLatency(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentOperationCount", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentOperationCount")
    @ResponseWrapper(localName = "getCurrentOperationCountResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentOperationCountResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentOperationCountRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentOperationCountResponse")
    public Float getCurrentOperationCount(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentHDDUsage", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentHDDUsage")
    @ResponseWrapper(localName = "getCurrentHDDUsageResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetCurrentHDDUsageResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentHDDUsageRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getCurrentHDDUsageResponse")
    public Float getCurrentHDDUsage(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLatestMonitoringData", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetLatestMonitoringData")
    @ResponseWrapper(localName = "getLatestMonitoringDataResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetLatestMonitoringDataResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getLatestMonitoringDataRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getLatestMonitoringDataResponse")
    public String getLatestMonitoringData();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMetricValue", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetMetricValue")
    @ResponseWrapper(localName = "getMetricValueResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.GetMetricValueResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getMetricValueRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/getMetricValueResponse")
    public Float getMetricValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Node arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "enforceAction", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.EnforceAction")
    @ResponseWrapper(localName = "enforceActionResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.EnforceActionResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/enforceActionRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/enforceActionResponse")
    public void enforceAction(
        @WebParam(name = "arg0", targetNamespace = "")
        Node arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Node arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "submitElasticityRequirements", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.SubmitElasticityRequirements")
    @ResponseWrapper(localName = "submitElasticityRequirementsResponse", targetNamespace = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/", className = "at.ac.tuwien.dsg.sybl.monitorandenforcement.runtimeapi.SubmitElasticityRequirementsResponse")
    @Action(input = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/submitElasticityRequirementsRequest", output = "http://runtimeAPI.monitorandenforcement.sybl.dsg.tuwien.ac.at/SyblAPIService/submitElasticityRequirementsResponse")
    public void submitElasticityRequirements(
        @WebParam(name = "arg0", targetNamespace = "")
        List<ElasticityRequirement> arg0);

}
